import JSZip from "jszip";
import type { CompileResult, VerifyResult } from "../shared/types.js";
import { ensureAgentContracts } from "./agent-contracts.js";

export async function buildSubmissionPackage(
  compilation: CompileResult,
  verification: VerifyResult
): Promise<Buffer> {
  const zip = new JSZip();
  const root = zip.folder(compilation.projectName) ?? zip;

  root.file("SKILL.md", compilation.skillMarkdown);
  root.file("policy.yaml", compilation.policyYaml);
  root.file(
    "fixtures.json",
    JSON.stringify(verification.fixtures, null, 2)
  );
  root.file(
    "receipts.jsonl",
    verification.receipts
      .map((receipt) => JSON.stringify(receipt))
      .join("\n")
      .concat(verification.receipts.length ? "\n" : "")
  );
  root.file(
    "proof_bundle.json",
    JSON.stringify(verification.proofBundle, null, 2)
  );
  root.file(
    "rag_evidence.json",
    JSON.stringify(compilation.ragMatches || [], null, 2)
  );
  const proofActions =
    verification.proofBundle.actionContract &&
    typeof verification.proofBundle.actionContract === "object" &&
    "events" in verification.proofBundle.actionContract &&
    Array.isArray(verification.proofBundle.actionContract.events)
      ? verification.proofBundle.actionContract.events
      : [];
  const contracts = ensureAgentContracts({
    actions: proofActions,
    fixtures: compilation.fixtures,
    harnessContract:
      (verification.proofBundle.harnessContract as
        | CompileResult["harnessContract"]
        | undefined) || compilation.harnessContract,
    verifierContract:
      (verification.proofBundle.verifierContract as
        | CompileResult["verifierContract"]
        | undefined) || compilation.verifierContract
  });
  const harnessContract = contracts.harnessContract;
  const verifierContract = contracts.verifierContract;
  if (harnessContract) {
    root.file(
      "harness.json",
      JSON.stringify(harnessContract, null, 2)
    );
  }
  if (verifierContract) {
    root.file(
      "verifier.json",
      JSON.stringify(verifierContract, null, 2)
    );
  }
  root.file(
    "verifier_feedback.json",
    JSON.stringify(
      verification.feedback || {
        schemaVersion: "0.1.0",
        findings: [],
        autoRepairEligible: false,
        generatedAt: verification.proofBundle.createdAt || "legacy"
      },
      null,
      2
    )
  );
  if (compilation.revisionHistory?.length) {
    root.file(
      "revision_history.json",
      JSON.stringify(
        verification.proofBundle.revisionHistory ||
          compilation.revisionHistory,
        null,
        2
      )
    );
  }
  const actionContract = verification.proofBundle.actionContract;
  if (actionContract) {
    root.file(
      "action_contract.json",
      JSON.stringify(actionContract, null, 2)
    );
  }
  const sandboxReplay = verification.proofBundle.sandboxReplay;
  if (sandboxReplay) {
    root.file(
      "sandbox_replay.json",
      JSON.stringify(sandboxReplay, null, 2)
    );
  }
  if (compilation.voiceEvidence) {
    root.file(
      "voice_evidence.json",
      JSON.stringify(
        {
          ...compilation.voiceEvidence,
          transcriptReviewed: compilation.voiceEvidenceReviewed || false,
          transcriptModified: compilation.voiceTranscriptModified || false,
          rawAudioIncluded: false
        },
        null,
        2
      )
    );
  }
  root.file(
    "README.md",
    `# ${compilation.projectName}

Generated by Radeon Voice Skill Foundry.

Status: ${verification.status}

## Contents

- \`SKILL.md\`: portable Agent Skill Markdown
- \`policy.yaml\`: generated capability decisions
- \`fixtures.json\`: positive and negative verification fixtures
- \`receipts.jsonl\`: append-only governance decisions
- \`proof_bundle.json\`: hashes, runtime metadata, and verification evidence
- \`harness.json\`: server-authoritative tools, context, memory, sandbox, and execution budgets
- \`verifier.json\`: independent completion criteria and repair policy
- \`verifier_feedback.json\`: structured findings and bounded repair guidance
- \`action_contract.json\`: server-authoritative demonstration events and hash
- \`sandbox_replay.json\`: step-by-step state hashes, diffs, and adversarial probes
${compilation.revisionHistory?.length ? "- `revision_history.json`: natural-language turns, parent-child run lineage, policy deltas, and verification state" : ""}
${compilation.voiceEvidence ? "- `voice_evidence.json`: derived audio-quality evidence and source hash" : ""}
- \`proof_bundle.json.compatibility\`: verifier, runtime, tool, policy, and skill compatibility manifest
`
  );

  return zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 9 }
  });
}
