import JSZip from "jszip";
import type { CompileResult, VerifyResult } from "../shared/types.js";

export async function buildSubmissionPackage(
  compilation: CompileResult,
  verification: VerifyResult
): Promise<Buffer> {
  const zip = new JSZip();
  const root = zip.folder(compilation.projectName) ?? zip;

  root.file("SKILL.md", compilation.skillMarkdown);
  root.file("policy.yaml", compilation.policyYaml);
  root.file(
    "fixtures.json",
    JSON.stringify(verification.fixtures, null, 2)
  );
  root.file(
    "receipts.jsonl",
    verification.receipts
      .map((receipt) => JSON.stringify(receipt))
      .join("\n")
      .concat(verification.receipts.length ? "\n" : "")
  );
  root.file(
    "proof_bundle.json",
    JSON.stringify(verification.proofBundle, null, 2)
  );
  root.file(
    "rag_evidence.json",
    JSON.stringify(compilation.ragMatches || [], null, 2)
  );
  if (compilation.voiceEvidence) {
    root.file(
      "voice_evidence.json",
      JSON.stringify(
        {
          ...compilation.voiceEvidence,
          transcriptReviewed: compilation.voiceEvidenceReviewed || false,
          transcriptModified: compilation.voiceTranscriptModified || false,
          rawAudioIncluded: false
        },
        null,
        2
      )
    );
  }
  root.file(
    "README.md",
    `# ${compilation.projectName}

Generated by Radeon Voice Skill Foundry.

Status: ${verification.status}

## Contents

- \`SKILL.md\`: GAIA-compatible skill
- \`policy.yaml\`: generated capability decisions
- \`fixtures.json\`: positive and negative verification fixtures
- \`receipts.jsonl\`: append-only governance decisions
- \`proof_bundle.json\`: hashes, runtime metadata, and verification evidence
${compilation.voiceEvidence ? "- `voice_evidence.json`: derived audio-quality evidence and source hash" : ""}
`
  );

  return zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 9 }
  });
}
